# Generated by Django 5.2.1 on 2025-05-11 13:54

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='Ajman', max_length=50)),
                ('center', models.CharField(default='Abdullah bin Rashid Al Nuaimi - Male', max_length=100)),
                ('center_type', models.CharField(default='Halaqa', max_length=50)),
                ('region', models.CharField(default='Al Rawdah', max_length=50)),
                ('session_time', models.CharField(default='Evening', max_length=50)),
                ('teacher', models.CharField(default='Sheikh Rashid Al-Habshi', max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('university', 'University Students'), ('school', 'School Students'), ('graduate', 'Graduates')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('registration_date', models.DateField()),
                ('study_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('phone_number', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=students.models.certificate_path)),
                ('issue_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
