# Generated by Django 4.2.21 on 2025-05-11 14:07

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date'], 'verbose_name': 'شهادة', 'verbose_name_plural': 'الشهادات'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to=students.models.certificate_path, verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Ajman', max_length=50, verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('university', 'طالب جامعي'), ('school', 'طالب مدرسة'), ('graduate', 'خريج')], max_length=20, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='center',
            field=models.CharField(default='Abdullah bin Rashid Al Nuaimi - Male', max_length=100, verbose_name='المركز'),
        ),
        migrations.AlterField(
            model_name='student',
            name='center_type',
            field=models.CharField(default='Halaqa', max_length=50, verbose_name='نوع المركز'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=255, verbose_name='اسم ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=20, verbose_name='هاتف ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=10, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(default='Al Rawdah', max_length=50, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateField(verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_time',
            field=models.CharField(default='Evening', max_length=50, verbose_name='وقت الجلسة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='المستوى الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.CharField(default='Sheikh Rashid Al-Habshi', max_length=100, verbose_name='المعلم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
