# Generated by Django 5.2.1 on 2025-05-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('current_surah', models.IntegerField()),
                ('current_ayah', models.IntegerField()),
                ('target_ayahs_per_day', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Memorization Plan',
                'verbose_name_plural': 'Memorization Plans',
                'ordering': ['-week_start', 'student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_type', models.CharField(choices=[('new', 'New Memorization'), ('review', 'Review'), ('tajweed', 'Tajweed Rules'), ('fiqh', 'Fiqh of Worship'), ('jibal', 'Ya Jibal Oobi'), ('custom', 'Custom Lesson')], max_length=10)),
                ('surah_start', models.IntegerField(blank=True, null=True)),
                ('ayah_start', models.IntegerField(blank=True, null=True)),
                ('ayah_end', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.memorizationplan')),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
                'ordering': ['date', 'plan__student__full_name'],
            },
        ),
    ]
